### ISSUE TITLE
请问，项目是否仍在维护？

### ISSUE THREAD

**Issue by Ray-Eldath** [encorehu/qqunrobot#3]
如题。
若项目已停止维护，我可以尝试接手并重构代码。

**Comment by ice1000** [comment]
我特么直接搜索qq group 搜出来翻到issue区特么看到你了 这是不是一种缘分呢

**Comment by ice1000** [comment]
@Ray-Eldath

**Comment by Ray-Eldath** [comment]
啊，应该是吧。@ice1000
（滑稽）

**Comment by Ray-Eldath** [comment]
啊，应该是吧。@ice1000
（滑稽）

**Comment by Ray-Eldath** [comment]
啊，应该是吧。@ice1000
（滑稽）

**Comment by Ray-Eldath** [comment]
啊，应该是吧。@ice1000
（滑稽）

**Comment by Ray-Eldath** [comment]
啊，应该是吧。@ice1000
（滑稽）

**Comment by Ray-Eldath** [comment]
啊，应该是吧。@ice1000
（滑稽）

**Comment by Ray-Eldath** [comment]
啊，应该是吧。@ice1000
（滑稽）

**Comment by Ray-Eldath** [comment]
机房电脑刷新太慢。。一下就点多了

**Comment by ice1000** [comment]
我的邮箱受到了1w点伤害

**Comment by Ray-Eldath** [comment]
噫。。不是故意的@ice1000
话说这个开发者怎么还不回复@encorehu

**Comment by ice1000** [comment]
@encorehu

**Comment by encorehu** [comment]
没有维护了。webqq，腾讯没有搞了，现在要刷二维码，好些接口肯定还在，但是获取到这些接口比以前更难了。

**Comment by ice1000** [comment]
其实也还好 只要能登录就是吼的 谢谢了repo主 @encorehu 
我们走吧 @Ray-Eldath

**Comment by ice1000** [comment]
@Ray-Eldath 你是不是应该close掉这个issue了。
